version: "3.9"
services:
  webapp:
    build:
      context: .
      dockerfile: Docker/webapp/Dockerfile
    container_name: "hoge-blazor-web-app"
    networks:
      - appnet
    ports:
      - 80:80
    links:
      - postgres
      # - mysql
    command: [ "dotnet", "watch", "run" ]
  # mysql:
  #   container_name: hoge-blazor-mysql
  #   hostname: hoge-blazor-mysql
  #   build: ./Docker/mysql
  #   volumes:
  #     - ./Docker/mysql/db:/docker-entrypoint-initdb.d #初期データをマウントする場所
  #   networks:
  #     - appnet
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password #コンテナ内のMySQLを起動する際のパスワードを設定
  #   healthcheck:
  #     test: [ "CMD", "mysqladmin", "ping" ]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  postgres:
    container_name: hoge-blazor-postgres
    hostname: hoge-blazor-postgres
    build: ./Docker/postgres
    volumes:
      - ./Docker/postgres/data:/var/lib/postgresql/data
      - ./Docker/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - appnet
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s
networks:
  appnet:
    driver: bridge
    ipam:
      driver: default
