version: "3.1"
services:
  webapp:
    build:
      context: .
      dockerfile: Docker/webapp/Dockerfile
    container_name: "hoge-blazor-web-app"
    ports:
      - 80:80
     links:
      - mysql
    entrypoint:
      - dockerize
      - -timeout
      - 60s
      - -wait
      - tcp://mysql:3306
    command: [ "dotnet", "watch", "run" ]
  mysql:
    container_name: hoge-blazor-mysql
    hostname: hoge-blazor-mysql
    build: ./Docker/mysql
    volumes:
      - ./Docker/mysql/db:/docker-entrypoint-initdb.d #初期データをマウントする場所
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password #コンテナ内のMySQLを起動する際のパスワードを設定
