version: "3.9"
services:
  webapp:
    build:
      context: .
      dockerfile: Docker/webapp/Dockerfile
    container_name: "hoge-blazor-web-app"
    networks:
      - appnet
    ports:
      - 80:80
    links:
      - postgres
    command: [ "dotnet", "watch", "run" ]
  postgres:
    container_name: hoge-blazor-postgres
    hostname: hoge-blazor-postgres
    build: ./Docker/postgres
    volumes:
      - ./Docker/postgres/data:/var/lib/postgresql/data
      - ./Docker/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - appnet
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s
networks:
  appnet:
    driver: bridge
    ipam:
      driver: default
