FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /source
#WORKDIR /app
#EXPOSE 5000


COPY Client/. ./Client/
COPY Server/. ./Server/
COPY Shared/. ./Shared/
RUN dotnet build ./Server/HogeBlazor.Server.csproj
#RUN dotnet restore "./Server/HogeBlazor.Server.csproj"
#RUN dotnet build "./Server/HogeBlazor.Server.csproj" -c Release -o /app/build

WORKDIR /source/Server
RUN dotnet publish -c release
#WORKDIR /app/build
#RUN dotnet publish "./Server/HogeBlazor.Server.csproj" -c release -o /app/publish


#RUN dotnet publish "./Server/HogeBlazor.Server.csproj" -c release -o /app/publish
#WORKDIR /app/publish
# COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "run", "--project", "./Server/HogeBlazor.Server.csproj"]
